### ISSUE TITLE
Using lists of patterns for an entity.

### ISSUE THREAD

**Issue by rwblair** [grabbles/grabbit#12]
Is it currently possible to pass a list of patterns to be searched for to an entity? The pybids BIDSLayout class inherits directly from Layout and does not override the get function. I was not able to pass a list of patterns to get successfully:

```
>>> from bids.grabbids import BIDSLayout
>>> root = 'fake_data/BIDS-examples-1-enh-ds054/ds054/'
>>> layout = BIDSLayout(root)
>>> len(layout.get(ext='.nii'))
0
>>> len(layout.get(ext='.nii.gz'))
16
>>> len(layout.get(ext=['.nii', '.nii.gz']))
0
>>> 
```

Are there any changes I should make to how I am calling get?

**Comment by tyarkoni** [comment]
The argument is `extensions`, not `ext`, so that might be the issue. Lists should work. Also, extension matching uses regex, so in theory, passing '.nii.*' should also work fine, though I haven't tested it. Let me know if you still have problems.

**Comment by tyarkoni** [comment]
Actually, it's pretty weird to me that `len(layout.get(ext='.nii.gz'))` returns anything. That should fail, in my book, since `ext` is not a valid entity in the BIDS .json spec, and the argument is `extensions`.  So that's a bit puzzling.

**Comment by rwblair** [comment]
The config being used is from the pybids repository:
https://github.com/INCF/pybids/blob/master/bids/grabbids/config/bids.json


Interestingly if regex_match is enabled, the list of patterns works:
```
>>> len(layout.get(ext=['.nii', '.nii.gz'], regex_match=True))
35
>>> len(layout.get(ext=['.nii', '.nii.gz']))
0
```

**Comment by rwblair** [comment]
But with regex_match enabled, every file is matched, including json files. The total number of files found matches the len of the first layout.get from my last comment:
```
>>> len(layout.files)
35
>>> layout.get(ext=['.nii', '.nii.gz'], regex_match=True)[0]
File(filename='/root/src/fmriprep/test/fake_data/BIDS-examples-1-enh-ds054/ds054/phasediff.json', ext='.json')
```

**Comment by tyarkoni** [comment]
Oh, I somehow missed the 'ext' entity in bids.json. What's going on is that grabbit is looking at the actual extension of the file, which is handled separately from the 'ent' entity. Unless there's some good reason to define extension as its own entity, I would suggest dropping it and relying on the (more robust) `extensions` argument.

@chrisfilo, this also answers the question of what was going wrong in the last release. Because you're defining an 'ent' entity, it's treated like any other entity in file matching; so when you set `regex_match=False`, grabbit has no way of knowing that `ext` is a special entity to which standard matching rules don't apply. Because the standard matching does *not* accept lists, it craps out when you insist on a perfect match, because it's literally trying to match the string `'['.nii', '.nii.gz']'` inside the filename.

There are several possible solutions here. One is to allow list passing in grabbit. I can easily implement that, and should probably do that anyway—but it probably won't happen for a few days. But my suggestion with respect to the BIDS.json spec is to drop ent as an entity, since I think you can do everything you want to more flexibly with the built-in `extensions` argument, which also produce the desired behavior.

**Comment by rwblair** [comment]
Thank you @tyarkoni I will try using extensions as opposed to ext and see how it goes.

**Comment by tyarkoni** [comment]
@rwblair does the existing functionality meet your needs, and if so, can we close this issue?

**Comment by rwblair** [comment]
Should be good for now.

**Comment by yarikoptic** [comment]
Iirc lists of patterns not yet supported and I wanted them too fwiw ;-) should indeed be easy to implement and I would probably of noone else does
